# Generated by Django 5.0 on 2023-12-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
